qc:
  active-qmanager: localQM
  ui:
    font-size: 12
    window:
      columns: 100
      rows: 30
  ssl:
    keystore:
      location: "file:keystore.p12"
      password: "password"
      type: "PKCS12"
    truststore:
      location: "file:truststore.jks"
      password: "password"
      type: "JKS"
  qmanagers:
    - name: localQM
      url: http://localhost:8161/api/jolokia/
      username: admin
      password: admin
    - name: broker-intern1-test
      url: https://broker-1.mydomain.se:8161/api/jolokia/
      username: admin
      password: admin
    - name: broker-intern2-test
      url: https://broker-2.mydomain.se:8161/api/jolokia/
      username: admin
      password: admin