qc:
  ssl:
    keystore:
      location: "file:/Users/malen501/Development/certs/esbtest.vgregion.se-keystore.p12"
      password: "KEYSTORE_PASSWORD"
      type: "PKCS12"
    truststore:
      location: "/Users/malen501/Development/certs/truststore.jks"
      password: "pasword"
      type: "JKS"
  qmanagers:
    - name: localQM
      url: http://localhost:8161/api/jolokia/
      username: admin
      password: admin
    - name: broker-intern1-test
      url: https://broker-intern1-test.vgregion.se:8162/api/jolokia/
      username: admin
      password: admin
    - name: broker-intern2-test
      url: https://broker-intern2-test.vgregion.se:8162/api/jolokia/
      username: admin
      password: admin